// src/main/scala/framework/spec/SpecRegistry.scala
package framework.spec

import scala.collection.mutable.ListBuffer
import java.nio.file.{Files, Path}

/**
 * SpecRegistry: Central data registry object for the framework. All spec
 * definitions ([[HardwareSpecification]]) and `@LocalSpec` tag information
 * ([[Tag]]) are collected here at compile time. This object is used for
 * debugging and testing purposes; actual hardware spec management is not
 * performed here.
 */
object SpecRegistry {
  private[spec] val specBuf: ListBuffer[HardwareSpecification] =
    ListBuffer.empty[HardwareSpecification]
  private[spec] val tagBuf: ListBuffer[Tag]                    = ListBuffer.empty[Tag]

  /**
   * Add a new hardware specification definition to the registry.
   */
  def addSpec(spec: HardwareSpecification): Unit = {
    specBuf += spec
    println(
      s"[DEBUG SpecRegistry] addSpec called for ID: ${spec.id}. Current total specs: ${specBuf.size}",
    )
  }

  /**
   * Add tag information generated by the `@LocalSpec` annotation to the
   * registry.
   */
  def addTag(tag: Tag): Unit = {
    tagBuf += tag
    println(
      s"[DEBUG SpecRegistry] addTag called for ID: ${tag.id} (Src: ${tag.srcFile}:${tag.line}). Current total tags: ${tagBuf.size}",
    )
  }

  /**
   * Return all hardware specification definitions currently registered in the
   * registry.
   */
  def allSpecs: Seq[HardwareSpecification] = {
    val currentSpecs = specBuf.toSeq
    println(
      s"[DEBUG SpecRegistry] allSpecs called. Returning ${currentSpecs.size} specs.",
    )
    currentSpecs
  }

  /**
   * Return all tag information currently registered in the registry.
   */
  def allTags: Seq[Tag] = {
    val currentTags = tagBuf.toSeq
    println(
      s"[DEBUG SpecRegistry] allTags called. Returning ${currentTags.size} tags.",
    )
    currentTags
  }

  /**
   * Initialize the registry. (For test or build cleanup purposes)
   */
  def clear(): Unit = {
    specBuf.clear()
    tagBuf.clear()
    println("[DEBUG SpecRegistry] clear() called. Registry has been reset.")
  }

  // Dump all Tag objects as JSON (for plugin or SBT task use) - This part appears to be unused.
  // private lazy val jsonRepr: String = upickle.default.write(all, indent = 2)
  // def dumpTo(path: Path): Unit = Files.write(path, jsonRepr.getBytes)
}
