// spec-core/src/main/scala/framework/spec/Tag.scala
package framework.spec

import upickle.default.{macroRW, ReadWriter}

/**
 * Tag: A case class containing metadata generated by the `@LocalSpec` annotation macro.
 * This Tag object includes information indicating where a particular spec is tagged in the RTL code.
 * During the FIRRTL Transform phase, `fullyQualifiedModuleName` and `hardwareInstancePath` are populated.
 *
 * (Updated): The `specFqn` field was removed to match the TagIndex.json spec.
 * `fullyQualifiedModuleName` represents the full path of the Scala declaration where @LocalSpec is applied.
 *
 * @param id
 * Unique identifier ID of the spec ([[HardwareSpecification]]) referenced by this Tag.
 * Equivalent to `HardwareSpecification.id`.
 * @param fullyQualifiedModuleName
 * The fully qualified name (including package path) of the nearest Scala class or object enclosing the
 * Scala code element tagged with `@LocalSpec`. Used to identify the location in the source code.
 * @param hardwareInstancePath
 * The actual hardware instance path in the RTL hierarchy, filled after FIRRTL elaboration.
 * A hierarchical string of module/instance names separated by slashes (`/`) or dots (`.`),
 * e.g., "Top.Cpu.PipeStage".
 * @param srcFile
 * Absolute path of the original Scala source file with the `@LocalSpec` annotation.
 * @param line
 * Line number in the source file where the `@LocalSpec` annotation is present (1-based).
 * @param column
 * Column number in the source file where the `@LocalSpec` annotation is present (0-based).
 */
final case class Tag(
  id: String,
  scalaDeclarationPath: String, // Full path of the Scala declaration where @LocalSpec is applied
  fullyQualifiedModuleName: String, // FQN of the Scala element being tagged
  hardwareInstancePath: String,     // For FIRRTL elaboration
  srcFile: String,
  line: Int,
  column: Int
)

object Tag {
  /**
   * Defines the upickle ReadWriter for Tag.
   * For case classes, macroRW can automatically generate the ReadWriter.
   */
  implicit val rw: ReadWriter[Tag] = macroRW
}
